name: Test LTS Container Images

on: [push, pull_request]

jobs:
  test_images:
    name: Test LTS Container Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - apache
          - fpm-alpine
          - fpm
    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build Container images'
        uses: docker/build-push-action@v5
        with:
          context: 5.0/${{ matrix.context }}
          push: false
          load: true
          tags: docker.io/martialblog/limesurvey:5-${{ matrix.context }}

      - name: 'Run Structure tests'
        uses: plexsystems/container-structure-test-action@v0.3.0
        with:
          image: docker.io/martialblog/limesurvey:5-${{ matrix.context }}
          config: tests/${{ matrix.context }}-tests.yaml
