name: Test ARM Container Images

on:
  push:
    branches:
      - 'arm/**'
  pull_request:
    branches:
      - 'arm/**'

jobs:
  test_images:
    name: Test Latest Container Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - apache
          - fpm-alpine
          - fpm
        platform:
          - linux/arm64
    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@v3

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Build Container images'
        uses: docker/build-push-action@v4
        with:
          context: 6.0/${{ matrix.context }}
          push: false
          load: true
          tags: docker.io/martialblog/limesurvey:6-${{ matrix.context }}
          platforms: ${{ matrix.platform }}

      - name: 'Run Structure tests'
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
          image: docker.io/martialblog/limesurvey:6-${{ matrix.context }}
          config: tests/${{ matrix.context }}-tests.yaml
